project:
  type: website

website:
  title: "Jon Brauer"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Reluctant Criminologists"
        href: https://reluctantcriminologists.com/
      - text: "Course Materials"
        href: course-materials.qmd
  twitter-card: true

format:
  html:
    theme: morph
    css: styles.css

